### PR TITLE
DOC-11426 update dependencies

### PR DESCRIPTION
**Pull request by jpmarceau**
Someone reported an issue with the library https://github.com/coveo/search-ui-seed/issues/33
This PR should address said issue, which was due to missing/outdated dependencies.

Please clone this repo, check out this branch, and see if you can successfully run the commands as explained in this tutorial: https://levelup.coveo.com/learn/courses/jsui/lessons/javascript-search-framework-tutorial-0-environment-setup

Note, you'll need node 16 rather than 10. I have a PR opened in the training repo to update that:
https://github.com/coveo/coveo-training-content/pull/694

### CODE REVIEW

**Comment by npushkarskii** [comment]
it fails on the last command, `npm run watch`


image

**Comment by npushkarskii** [comment]
I'll try fixing the error on my end and run the command again 🤔

**Comment by npushkarskii** [comment]
Ok, once I manually installed `webpack-dev-server`, all the commands work fine 👍

I'm not sure, buy maybe we should make installation of `webpack-dev-server` automatic as well 🤔

image
image

**Comment by npushkarskii** [comment]
@jpmarceau 

Forget everything, I didn't check out this branch, ahahahahahah

Lemme quickly check it out while being in the correct branch, lol

**Review by npushkarskii — APPROVED** [review]
Perfecto! 👌

**Review by srosenberg-coveo — APPROVED** [review]
Works great on my end!

**Pull request merged**
